config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: 'sessions#failure'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get '/welcome', to: 'welcome#index'

  root to: 'welcome#index'

  namespace :admin do
    root to: 'dashboard#index'

    get '/dashboard', to: 'dashboard#index'

    post '/versions/revert', to: 'versions#revert', as: 'revert_version'

    resources :awaken_types
    resources :cards
    resources :characters
    resources :evidences, except: [:show, :edit, :update]
    resources :leader_skills
    resources :links
    resources :passive_skills
    resources :rarities
    resources :stat_types
    resources :super_attacks
    resources :types
    resources :users, except: [:new, :create]
    resources :versions, only: [:show]
  end

  constraints subdomain: /^api(\.|$)/ do
    namespace :api, path: nil do
      namespace :v1 do
        resources :cards, only: [:index, :show]
        resources :links, only: [:index, :show]
      end
    end
  end
end

app/models/awaken_type.rb
class AwakenType < ActiveRecord::Base
  has_paper_trail

  validates :name, presence: true,
                   uniqueness: { case_sensitive: false }
end

app/models/card.rb
class Card < ActiveRecord::Base
  has_paper_trail

  after_create :set_stat_types

  belongs_to :character
  belongs_to :rarity
  belongs_to :type
  belongs_to :leader_skill
  belongs_to :passive_skill
  belongs_to :super_attack
  belongs_to :awaken_type
  belongs_to :dokkan_card, class_name: 'Card', foreign_key: :dokkan_id

  has_and_belongs_to_many :links, counter_cache: true

  has_many :evidences

  belongs_to :hp_stat, class_name: 'Stat'
  belongs_to :atk_stat, class_name: 'Stat'
  belongs_to :def_stat, class_name: 'Stat'
  belongs_to :cost_stat, class_name: 'Stat'

  accepts_nested_attributes_for :hp_stat
  accepts_nested_attributes_for :atk_stat
  accepts_nested_attributes_for :def_stat
  accepts_nested_attributes_for :cost_stat

  delegate :name, to: :character, prefix: false

  validates :title, presence: true
  validates :character, presence: true
  validates :gameid, presence: true,
                     numericality: { only_integer: true },
                     length: { is: 7 }
  validates :rarity, presence: true
  validates :type, presence: true
  validates :awaken_type, presence: true

  scope :new_this_week, -> { where('created_at > ?', 1.week.ago) }

  def dokkan?
    dokkan_id != nil
  end

  def full_name
    "#{title} #{character.name}"
  end

  def icon
    "card_#{gameid}_thumb.png"
  end

  def self.verified
    Card.where(verified: true)
  end

  private

  def set_stat_types
    self.hp_stat.stat_type_id = 1
    self.atk_stat.stat_type_id = 2
    self.def_stat.stat_type_id = 3
    self.cost_stat.stat_type_id = 4

    self.save
  end
end

app/models/cards_link.rb
class CardsLink < ActiveRecord::Base
  belongs_to :card
  belongs_to :link
end

app/models/character.rb
class Character < ActiveRecord::Base
  has_paper_trail

  validates :name, presence: true,
                   uniqueness: { case_sensitive: false }

  default_scope { order(:name) }
end

app/models/evidence.rb
class Evidence < ActiveRecord::Base
  has_attached_file :screenshot, styles: {
                                            thumb: 'x100',
                                            small: 'x200',
                                            medium: 'x400',
                                            big: 'x600'
                                          }

  belongs_to :card

  scope :unused, -> { where(card_id: nil) }
  scope :for, -> (id) { where(card_id: id) }

  validates_attachment_content_type :screenshot, content_type: /\Aimage\/.*\Z/
end

app/models/guest_user.rb
class GuestUser
  def admin?
    false
  end

  def moderator?
    false
  end
end

app/models/leader_skill.rb
class LeaderSkill < ActiveRecord::Base
  has_paper_trail

  validates :description, presence: true,
                          uniqueness: { case_sensitive: false }

  default_scope { order(:description) }
end

app/models/link.rb
class Link < ActiveRecord::Base
  has_paper_trail

  has_and_belongs_to_many :cards

  validates :name, presence: true,
                   uniqueness: true

  default_scope { order(:name) }

  def self.issues
    Link.where(description: nil)
  end
end

app/models/medal.rb
class Medal < ActiveRecord::Base
end

app/models/rarity.rb
class Rarity < ActiveRecord::Base
  has_paper_trail

  validates :name, presence: true,
                   uniqueness: { case_sensitive: false }
  validates :description, presence: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/stat.rb
class Stat < ActiveRecord::Base
  belongs_to :state_type
end

app/models/stat_type.rb
class StatType < ActiveRecord::Base
  has_paper_trail

  validates :name, presence: true,
                   uniqueness: { case_sensitive: false }
  validates :description, presence: true
end

app/models/super_attack.rb
class SuperAttack < ActiveRecord::Base
  has_paper_trail

  validates :name, presence: true
  validates :description, presence: true,
                          uniqueness: { scope: :name }

  default_scope { order(:name) }

  def full
    "#{name} - #{description}"
  end

  def self.issues
    SuperAttack.where("name = '' OR description = ''")
  end
end

app/models/type.rb
class Type < ActiveRecord::Base
  has_paper_trail

  validates :name, presence: true,
                   uniqueness: { case_sensitive: false }
  validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_paper_trail
  rolify

  after_create :set_admin, if: :first_user?

  def self.create_with_omniauth(auth)
    where(provider: auth[:provider], uid: auth[:uid]).first_or_create do |user|
      user.provider = auth[:provider]
      user.uid      = auth[:uid]
      user.nickname = auth[:info][:name]
      user.email    = auth[:info][:email]
    end
  end

  def admin?
    self.has_role?(:admin)
  end

  def moderator?
    self.has_role?(:moderator)
  end

  def first_user?
    User.unscoped do
      User.count == 1
    end
  end

  private

  def set_admin
    self.add_role :admin
  end
end

app/helpers/cards_helper.rb
module CardsHelper
  def evidence_checkbox_label(evidence)
    link_to image_tag(evidence.screenshot.url(:thumb)),
      evidence.screenshot.url(:medium), class: 'img-preview'
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_navbar.html.slim
.navbar.navbar-default.navbar-static-top.navbar-custom
  .container
    .navbar-header
      button.navbar-toggle.collapsed type='button' data-toggle='collapse' data-target='.navbar-collapse'
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'DBZDokkan', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        li= link_to 'Administration', admin_root_path
      ul.nav.navbar-nav.navbar-right
        - if policy(:link).index? || policy(:leader_skill).index? || policy(:passive_skill).index? || policy(:super_attack).index?
          li.dropdown
            a href='#' class='dropdown-toggle' data-toggle='dropdown'
              = 'Abilities '
              span class='caret'
            ul.dropdown-menu
              - if policy(:link).index?
                li= link_to 'Links', admin_links_path
              - if policy(:leader_skill).index?
                li= link_to 'Leader Skills', admin_leader_skills_path
              - if policy(:passive_skill).index?
                li= link_to 'Passive Skills', admin_passive_skills_path
              - if policy(:super_attack).index?
                li= link_to 'Super Attacks', admin_super_attacks_path
        - if policy(:card).index?
          li= nav_link_to 'Cards', admin_cards_path
        - if policy(:character).index?
          li= nav_link_to 'Characters', admin_characters_path
        - if policy(:evidence).index?
          li= nav_link_to 'Evidence', admin_evidences_path
        - if policy(:awaken_type).index? || policy(:rarity).index? || policy(:type).index?
          li.dropdown
            a href='#' class='dropdown-toggle' data-toggle='dropdown'
              = 'Others '
              span class='caret'
            ul.dropdown-menu
              - if policy(:awaken_type).index?
                li= link_to 'Awaken Types', admin_awaken_types_path
              - if policy(:rarity).index?
                li= link_to 'Rarities', admin_rarities_path
              - if policy(:stat_type).index?
                li= link_to 'Stat Types', admin_stat_types_path
              - if policy(:type).index?
                li= link_to 'Types', admin_types_path
        - if policy(:user).index?
          li= nav_link_to 'Users', admin_users_path
        - if logged_in?
          li= link_to 'Log Out', logout_path, method: :delete
        - else
          li= link_to 'Log In', login_path(:reddit)